version: "3"
services:
#  main:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: main
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#    volumes:
#      - .:/usr/app
#      - /usr/app/node_modules
#    environment:
#      PGHOST: postgres
#      PGPORT: 5432
#      PGDATABASE: "nest_test_postgres"
#      PGUSER: "nest_test"
#      PGPASSWORD: "nest_test"
#    networks:
#      - main
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "nest_test_postgres"
      POSTGRES_USER: "nest_test"
      POSTGRES_PASSWORD: "nest_test"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_test
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis:/data
      - ./redis/redis-config:/usr/local/etc/redis
    networks:
      - redis-network

  redis_insight:
    container_name: redis_insight
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./redis/redis-insight:/db
    depends_on:
      - redis
    networks:
      - redis-network
volumes:
  redis:
  redis_insight:
networks:
  redis-network:
    driver: bridge