version: "3"
services:
#  main:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: main
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#    volumes:
#      - .:/usr/app
#      - /usr/app/node_modules
#    environment:
#      PGHOST: postgres
#      PGPORT: 5432
#      PGDATABASE: "nest_test_postgres"
#      PGUSER: "nest_test"
#      PGPASSWORD: "nest_test"
#    networks:
#      - webnet

  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nest_test_postgres
      POSTGRES_USER: nest_test
      POSTGRES_PASSWORD: nest_test
    networks:
      - webnet
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nest_test@admin.com
      PGADMIN_DEFAULT_PASSWORD: nest_test
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis:7
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - webnet
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
      HTTP_USER: root
      HTTP_PASSWORD: qwerty
    ports:
      - "8081:8081"
    networks:
      - webnet
    depends_on:
      - redis
networks:
  webnet:
volumes:
  pgdata:
  redis:
  redis-config: